project:
  type: website

website:
  title: "SMT201_karina"
  navbar:
    left: 
      - href: overview.qmd
        text: Overview 
      - href: ""
        text: Methodolgy
      - text: Results 
        href: ""
    right:
      - href: index.qmd
        text: Home
      - text: Team
        href: about.qmd
      - text: Results and Discussion
        href: "qgis2web/index.html"

format:
  html:
    theme: como
    css: styles.css
    toc: true

editor: visual

